// plugin-kit-playground/src/surfaces/react/previews/ButtonPreview.tsx
import { buttonPlaygroundMeta, buttonPlaygroundSpec } from '@verbb/plugin-kit-playground';

import { PlaygroundFromSpec } from '../shared/PlaygroundFromSpec.js';
import { buttonReactSectionRenderers } from '../button-sections.js';
import type { SurfacePreviewDefinition } from '../types.js';

function ButtonPreviewPage() {
    return (
        <PlaygroundFromSpec
            spec={buttonPlaygroundSpec}
            sectionRenderers={buttonReactSectionRenderers}
        />
    );
}

export const buttonPreview: SurfacePreviewDefinition = {
    id: 'button',
    title: buttonPlaygroundMeta.title,
    description: buttonPlaygroundMeta.description,
    Component: ButtonPreviewPage,
};

// plugin-kit-playground/src/surfaces/vue/previews/ButtonPreview.vue
<script setup lang="ts">
import { buttonPlaygroundSpec } from '@verbb/plugin-kit-playground';

import PlaygroundFromSpec from '../shared/PlaygroundFromSpec.vue';
import { buttonVueSectionComponents } from '../button-sections/index.js';
</script>

<template>
  <PlaygroundFromSpec
    :spec="buttonPlaygroundSpec"
    :section-components="buttonVueSectionComponents"
  />
</template>
