// plugin-kit-playground/src/surfaces/react/previews/CalendarPreview.tsx
import { calendarPlaygroundMeta, calendarPlaygroundSpec } from '@verbb/plugin-kit-playground';

import { calendarReactSectionRenderers } from '../calendar-sections.js';
import { PlaygroundFromSpec } from '../shared/PlaygroundFromSpec.js';
import type { SurfacePreviewDefinition } from '../types.js';

function CalendarPreviewPage() {
    return (
        <PlaygroundFromSpec
            spec={calendarPlaygroundSpec}
            sectionRenderers={calendarReactSectionRenderers}
        />
    );
}

export const calendarPreview: SurfacePreviewDefinition = {
    id: 'calendar',
    title: calendarPlaygroundMeta.title,
    description: calendarPlaygroundMeta.description,
    Component: CalendarPreviewPage,
};

// plugin-kit-playground/src/surfaces/vue/previews/CalendarPreview.vue
<script setup lang="ts">
import { calendarPlaygroundSpec } from '@verbb/plugin-kit-playground';

import PlaygroundFromSpec from '../shared/PlaygroundFromSpec.vue';
import { calendarVueSectionComponents } from '../spec-sections.js';
</script>

<template>
  <PlaygroundFromSpec
    :spec="calendarPlaygroundSpec"
    :section-components="calendarVueSectionComponents"
  />
</template>
