// plugin-kit-playground/src/surfaces/react/previews/ColorInputPreview.tsx
import { colorInputPlaygroundMeta, colorInputPlaygroundSpec } from '@verbb/plugin-kit-playground';

import { colorInputReactSectionRenderers } from '../color-input-sections.js';
import { PlaygroundFromSpec } from '../shared/PlaygroundFromSpec.js';
import type { SurfacePreviewDefinition } from '../types.js';

function ColorInputPreviewPage() {
    return (
        <PlaygroundFromSpec
            spec={colorInputPlaygroundSpec}
            sectionRenderers={colorInputReactSectionRenderers}
        />
    );
}

export const colorInputPreview: SurfacePreviewDefinition = {
    id: 'color-input',
    title: colorInputPlaygroundMeta.title,
    description: colorInputPlaygroundMeta.description,
    Component: ColorInputPreviewPage,
};

// plugin-kit-playground/src/surfaces/vue/previews/ColorInputPreview.vue
<script setup lang="ts">
import { colorInputPlaygroundSpec } from '@verbb/plugin-kit-playground';

import PlaygroundFromSpec from '../shared/PlaygroundFromSpec.vue';
import { colorInputVueSectionComponents } from '../color-input-sections/index.js';
</script>

<template>
  <PlaygroundFromSpec
    :spec="colorInputPlaygroundSpec"
    :section-components="colorInputVueSectionComponents"
  />
</template>
