// plugin-kit-playground/src/surfaces/react/previews/ComboboxPreview.tsx
import { comboboxPlaygroundMeta, comboboxPlaygroundSpec } from '@verbb/plugin-kit-playground';

import { comboboxReactSectionRenderers } from '../combobox-sections.js';
import { PlaygroundFromSpec } from '../shared/PlaygroundFromSpec.js';
import type { SurfacePreviewDefinition } from '../types.js';

function ComboboxPreviewPage() {
    return (
        <PlaygroundFromSpec
            spec={comboboxPlaygroundSpec}
            sectionRenderers={comboboxReactSectionRenderers}
        />
    );
}

export const comboboxPreview: SurfacePreviewDefinition = {
    id: 'combobox',
    title: comboboxPlaygroundMeta.title,
    description: comboboxPlaygroundMeta.description,
    Component: ComboboxPreviewPage,
};

// plugin-kit-playground/src/surfaces/vue/previews/ComboboxPreview.vue
<script setup lang="ts">
import { comboboxPlaygroundSpec } from '@verbb/plugin-kit-playground';

import PlaygroundFromSpec from '../shared/PlaygroundFromSpec.vue';
import { comboboxVueSectionComponents } from '../combobox-sections/index.js';
</script>

<template>
  <PlaygroundFromSpec
    :spec="comboboxPlaygroundSpec"
    :section-components="comboboxVueSectionComponents"
  />
</template>
