// plugin-kit-playground/src/surfaces/react/previews/CopyButtonPreview.tsx
import { copyButtonPlaygroundMeta, copyButtonPlaygroundSpec } from '@verbb/plugin-kit-playground';

import { copyButtonReactSectionRenderers } from '../copy-button-sections.js';
import { PlaygroundFromSpec } from '../shared/PlaygroundFromSpec.js';
import type { SurfacePreviewDefinition } from '../types.js';

function CopyButtonPreviewPage() {
    return (
        <PlaygroundFromSpec
            spec={copyButtonPlaygroundSpec}
            sectionRenderers={copyButtonReactSectionRenderers}
        />
    );
}

export const copyButtonPreview: SurfacePreviewDefinition = {
    id: 'copy-button',
    title: copyButtonPlaygroundMeta.title,
    description: copyButtonPlaygroundMeta.description,
    Component: CopyButtonPreviewPage,
};

// plugin-kit-playground/src/surfaces/vue/previews/CopyButtonPreview.vue
<script setup lang="ts">
import { copyButtonPlaygroundSpec } from '@verbb/plugin-kit-playground';

import PlaygroundFromSpec from '../shared/PlaygroundFromSpec.vue';
import { copyButtonVueSectionComponents } from '../copy-button-sections/index.js';
</script>

<template>
  <PlaygroundFromSpec
    :spec="copyButtonPlaygroundSpec"
    :section-components="copyButtonVueSectionComponents"
  />
</template>
