// plugin-kit-playground/src/surfaces/react/previews/DropdownMenuPreview.tsx
import { dropdownMenuPlaygroundMeta, dropdownMenuPlaygroundSpec } from '@verbb/plugin-kit-playground';

import { dropdownMenuReactSectionRenderers } from '../dropdown-menu-sections.js';
import { PlaygroundFromSpec } from '../shared/PlaygroundFromSpec.js';
import type { SurfacePreviewDefinition } from '../types.js';

function DropdownMenuPreviewPage() {
    return (
        <PlaygroundFromSpec
            spec={dropdownMenuPlaygroundSpec}
            sectionRenderers={dropdownMenuReactSectionRenderers}
        />
    );
}

export const dropdownMenuPreview: SurfacePreviewDefinition = {
    id: 'dropdown-menu',
    title: dropdownMenuPlaygroundMeta.title,
    description: dropdownMenuPlaygroundMeta.description,
    Component: DropdownMenuPreviewPage,
};

// plugin-kit-playground/src/surfaces/vue/previews/DropdownMenuPreview.vue
<script setup lang="ts">
import { dropdownMenuPlaygroundSpec } from '@verbb/plugin-kit-playground';

import PlaygroundFromSpec from '../shared/PlaygroundFromSpec.vue';
import { dropdownMenuVueSectionComponents } from '../dropdown-menu-sections/index.js';
</script>

<template>
  <PlaygroundFromSpec
    :spec="dropdownMenuPlaygroundSpec"
    :section-components="dropdownMenuVueSectionComponents"
  />
</template>
