// plugin-kit-playground/src/surfaces/react/previews/FieldPreview.tsx
import { fieldPlaygroundMeta, fieldPlaygroundSpec } from '@verbb/plugin-kit-playground';

import { fieldReactSectionRenderers } from '../field-sections.js';
import { PlaygroundFromSpec } from '../shared/PlaygroundFromSpec.js';
import type { SurfacePreviewDefinition } from '../types.js';

function FieldPreviewPage() {
    return (
        <PlaygroundFromSpec
            spec={fieldPlaygroundSpec}
            sectionRenderers={fieldReactSectionRenderers}
        />
    );
}

export const fieldPreview: SurfacePreviewDefinition = {
    id: 'field',
    title: fieldPlaygroundMeta.title,
    description: fieldPlaygroundMeta.description,
    Component: FieldPreviewPage,
};

// plugin-kit-playground/src/surfaces/vue/previews/FieldPreview.vue
<script setup lang="ts">
import { fieldPlaygroundSpec } from '@verbb/plugin-kit-playground';

import PlaygroundFromSpec from '../shared/PlaygroundFromSpec.vue';
import { fieldVueSectionComponents } from '../field-sections/index.js';
</script>

<template>
  <PlaygroundFromSpec
    :spec="fieldPlaygroundSpec"
    :section-components="fieldVueSectionComponents"
  />
</template>
