// plugin-kit-playground/src/surfaces/react/previews/InputPreview.tsx
import { inputPlaygroundMeta, inputPlaygroundSpec } from '@verbb/plugin-kit-playground';

import { inputReactSectionRenderers } from '../input-sections.js';
import { PlaygroundFromSpec } from '../shared/PlaygroundFromSpec.js';
import type { SurfacePreviewDefinition } from '../types.js';

function InputPreviewPage() {
    return (
        <PlaygroundFromSpec
            spec={inputPlaygroundSpec}
            sectionRenderers={inputReactSectionRenderers}
        />
    );
}

export const inputPreview: SurfacePreviewDefinition = {
    id: 'input',
    title: inputPlaygroundMeta.title,
    description: inputPlaygroundMeta.description,
    Component: InputPreviewPage,
};

// plugin-kit-playground/src/surfaces/vue/previews/InputPreview.vue
<script setup lang="ts">
import { inputPlaygroundSpec } from '@verbb/plugin-kit-playground';

import PlaygroundFromSpec from '../shared/PlaygroundFromSpec.vue';
import { inputVueSectionComponents } from '../input-sections/index.js';
</script>

<template>
  <PlaygroundFromSpec
    :spec="inputPlaygroundSpec"
    :section-components="inputVueSectionComponents"
  />
</template>
