// plugin-kit-playground/src/surfaces/react/previews/PopoverPreview.tsx
import { popoverPlaygroundMeta, popoverPlaygroundSpec } from '@verbb/plugin-kit-playground';

import { popoverReactSectionRenderers } from '../popover-sections.js';
import { PlaygroundFromSpec } from '../shared/PlaygroundFromSpec.js';
import type { SurfacePreviewDefinition } from '../types.js';

function PopoverPreviewPage() {
    return (
        <PlaygroundFromSpec
            spec={popoverPlaygroundSpec}
            sectionRenderers={popoverReactSectionRenderers}
        />
    );
}

export const popoverPreview: SurfacePreviewDefinition = {
    id: 'popover',
    title: popoverPlaygroundMeta.title,
    description: popoverPlaygroundMeta.description,
    Component: PopoverPreviewPage,
};

// plugin-kit-playground/src/surfaces/vue/previews/PopoverPreview.vue
<script setup lang="ts">
import { popoverPlaygroundSpec } from '@verbb/plugin-kit-playground';

import PlaygroundFromSpec from '../shared/PlaygroundFromSpec.vue';
import { popoverVueSectionComponents } from '../popover-sections/index.js';
</script>

<template>
  <PlaygroundFromSpec
    :spec="popoverPlaygroundSpec"
    :section-components="popoverVueSectionComponents"
  />
</template>
