// plugin-kit-playground/src/surfaces/react/previews/RadioGroupPreview.tsx
import { radioGroupPlaygroundMeta, radioGroupPlaygroundSpec } from '@verbb/plugin-kit-playground';

import { radioGroupReactSectionRenderers } from '../radio-group-sections.js';
import { PlaygroundFromSpec } from '../shared/PlaygroundFromSpec.js';
import type { SurfacePreviewDefinition } from '../types.js';

function RadioGroupPreviewPage() {
    return (
        <PlaygroundFromSpec
            spec={radioGroupPlaygroundSpec}
            sectionRenderers={radioGroupReactSectionRenderers}
        />
    );
}

export const radioGroupPreview: SurfacePreviewDefinition = {
    id: 'radio-group',
    title: radioGroupPlaygroundMeta.title,
    description: radioGroupPlaygroundMeta.description,
    Component: RadioGroupPreviewPage,
};

// plugin-kit-playground/src/surfaces/vue/previews/RadioGroupPreview.vue
<script setup lang="ts">
import { radioGroupPlaygroundSpec } from '@verbb/plugin-kit-playground';

import PlaygroundFromSpec from '../shared/PlaygroundFromSpec.vue';
import { radioGroupVueSectionComponents } from '../radio-group-sections/index.js';
</script>

<template>
  <PlaygroundFromSpec
    :spec="radioGroupPlaygroundSpec"
    :section-components="radioGroupVueSectionComponents"
  />
</template>
