// plugin-kit-playground/src/surfaces/react/previews/SpinnerPreview.tsx
import { spinnerPlaygroundMeta, spinnerPlaygroundSpec } from '@verbb/plugin-kit-playground';

import { spinnerReactSectionRenderers } from '../spinner-sections.js';
import { PlaygroundFromSpec } from '../shared/PlaygroundFromSpec.js';
import type { SurfacePreviewDefinition } from '../types.js';

function SpinnerPreviewPage() {
    return (
        <PlaygroundFromSpec
            spec={spinnerPlaygroundSpec}
            sectionRenderers={spinnerReactSectionRenderers}
        />
    );
}

export const spinnerPreview: SurfacePreviewDefinition = {
    id: 'spinner',
    title: spinnerPlaygroundMeta.title,
    description: spinnerPlaygroundMeta.description,
    Component: SpinnerPreviewPage,
};

// plugin-kit-playground/src/surfaces/vue/previews/SpinnerPreview.vue
<script setup lang="ts">
import { spinnerPlaygroundSpec } from '@verbb/plugin-kit-playground';

import PlaygroundFromSpec from '../shared/PlaygroundFromSpec.vue';
import { spinnerVueSectionComponents } from '../spinner-sections/index.js';
</script>

<template>
  <PlaygroundFromSpec
    :spec="spinnerPlaygroundSpec"
    :section-components="spinnerVueSectionComponents"
  />
</template>
