// plugin-kit-playground/src/surfaces/react/previews/StatusPreview.tsx
import { statusPlaygroundMeta, statusPlaygroundSpec } from '@verbb/plugin-kit-playground';

import { statusReactSectionRenderers } from '../status-sections.js';
import { PlaygroundFromSpec } from '../shared/PlaygroundFromSpec.js';
import type { SurfacePreviewDefinition } from '../types.js';

function StatusPreviewPage() {
    return (
        <PlaygroundFromSpec
            spec={statusPlaygroundSpec}
            sectionRenderers={statusReactSectionRenderers}
        />
    );
}

export const statusPreview: SurfacePreviewDefinition = {
    id: 'status',
    title: statusPlaygroundMeta.title,
    description: statusPlaygroundMeta.description,
    Component: StatusPreviewPage,
};

// plugin-kit-playground/src/surfaces/vue/previews/StatusPreview.vue
<script setup lang="ts">
import { statusPlaygroundSpec } from '@verbb/plugin-kit-playground';

import PlaygroundFromSpec from '../shared/PlaygroundFromSpec.vue';
import { statusVueSectionComponents } from '../status-sections/index.js';
</script>

<template>
  <PlaygroundFromSpec
    :spec="statusPlaygroundSpec"
    :section-components="statusVueSectionComponents"
  />
</template>
