// plugin-kit-playground/src/surfaces/react/previews/TabsPreview.tsx
import { tabsPlaygroundMeta, tabsPlaygroundSpec } from '@verbb/plugin-kit-playground';

import { tabsReactSectionRenderers } from '../tabs-sections.js';
import { PlaygroundFromSpec } from '../shared/PlaygroundFromSpec.js';
import type { SurfacePreviewDefinition } from '../types.js';

function TabsPreviewPage() {
    return (
        <PlaygroundFromSpec
            spec={tabsPlaygroundSpec}
            sectionRenderers={tabsReactSectionRenderers}
        />
    );
}

export const tabsPreview: SurfacePreviewDefinition = {
    id: 'tabs',
    title: tabsPlaygroundMeta.title,
    description: tabsPlaygroundMeta.description,
    Component: TabsPreviewPage,
};

// plugin-kit-playground/src/surfaces/vue/previews/TabsPreview.vue
<script setup lang="ts">
import { tabsPlaygroundSpec } from '@verbb/plugin-kit-playground';

import PlaygroundFromSpec from '../shared/PlaygroundFromSpec.vue';
import { tabsVueSectionComponents } from '../tabs-sections/index.js';
</script>

<template>
  <PlaygroundFromSpec
    :spec="tabsPlaygroundSpec"
    :section-components="tabsVueSectionComponents"
  />
</template>
