// plugin-kit-playground/src/surfaces/react/previews/TimePickerPreview.tsx
import { timePickerPlaygroundMeta, timePickerPlaygroundSpec } from '@verbb/plugin-kit-playground';

import { timePickerReactSectionRenderers } from '../time-picker-sections.js';
import { PlaygroundFromSpec } from '../shared/PlaygroundFromSpec.js';
import type { SurfacePreviewDefinition } from '../types.js';

function TimePickerPreviewPage() {
    return (
        <PlaygroundFromSpec
            spec={timePickerPlaygroundSpec}
            sectionRenderers={timePickerReactSectionRenderers}
        />
    );
}

export const timePickerPreview: SurfacePreviewDefinition = {
    id: 'time-picker',
    title: timePickerPlaygroundMeta.title,
    description: timePickerPlaygroundMeta.description,
    Component: TimePickerPreviewPage,
};

// plugin-kit-playground/src/surfaces/vue/previews/TimePickerPreview.vue
<script setup lang="ts">
import { timePickerPlaygroundSpec } from '@verbb/plugin-kit-playground';

import PlaygroundFromSpec from '../shared/PlaygroundFromSpec.vue';
import { timePickerVueSectionComponents } from '../time-picker-sections/index.js';
</script>

<template>
  <PlaygroundFromSpec
    :spec="timePickerPlaygroundSpec"
    :section-components="timePickerVueSectionComponents"
  />
</template>
