// plugin-kit-playground/src/surfaces/react/previews/TiptapEditorPreview.tsx
import { tiptapEditorPlaygroundMeta, tiptapEditorPlaygroundSpec } from '@verbb/plugin-kit-playground';

import { tiptapEditorReactSectionRenderers } from '../tiptap-editor-sections.js';
import { PlaygroundFromSpec } from '../shared/PlaygroundFromSpec.js';
import type { SurfacePreviewDefinition } from '../types.js';

function TiptapEditorPreviewPage() {
    return (
        <PlaygroundFromSpec
            spec={tiptapEditorPlaygroundSpec}
            sectionRenderers={tiptapEditorReactSectionRenderers}
        />
    );
}

export const tiptapEditorPreview: SurfacePreviewDefinition = {
    id: 'tiptap-editor',
    title: tiptapEditorPlaygroundMeta.title,
    description: tiptapEditorPlaygroundMeta.description,
    Component: TiptapEditorPreviewPage,
};

// plugin-kit-playground/src/surfaces/vue/previews/TiptapEditorPreview.vue
<script setup lang="ts">
import { tiptapEditorPlaygroundSpec } from '@verbb/plugin-kit-playground';

import PlaygroundFromSpec from '../shared/PlaygroundFromSpec.vue';
import { tiptapEditorVueSectionComponents } from '../tiptap-editor-sections/index.js';
</script>

<template>
  <PlaygroundFromSpec
    :spec="tiptapEditorPlaygroundSpec"
    :section-components="tiptapEditorVueSectionComponents"
  />
</template>
