// plugin-kit-playground/src/surfaces/react/previews/TiptapInputPreview.tsx
import { tiptapInputPlaygroundSpec } from '@verbb/plugin-kit-playground';

import { tiptapInputReactSectionRenderers } from '../tiptap-input-sections.js';
import { PlaygroundFromSpec } from '../shared/PlaygroundFromSpec.js';
import type { SurfacePreviewDefinition } from '../types.js';

function TiptapInputPreviewPage() {
    return (
        <PlaygroundFromSpec
            spec={tiptapInputPlaygroundSpec}
            sectionRenderers={tiptapInputReactSectionRenderers}
        />
    );
}

export const tiptapInputPreview: SurfacePreviewDefinition = {
    id: 'tiptap-input',
    title: tiptapInputPlaygroundSpec.meta.title,
    description: tiptapInputPlaygroundSpec.meta.description,
    Component: TiptapInputPreviewPage,
};

// plugin-kit-playground/src/surfaces/vue/previews/TiptapInputPreview.vue
<script setup lang="ts">
import { tiptapInputPlaygroundSpec } from '@verbb/plugin-kit-playground';

import PlaygroundFromSpec from '../shared/PlaygroundFromSpec.vue';
import { tiptapInputVueSectionComponents } from '../tiptap-input-sections/index.js';
</script>

<template>
  <PlaygroundFromSpec
    :spec="tiptapInputPlaygroundSpec"
    :section-components="tiptapInputVueSectionComponents"
  />
</template>
