// plugin-kit-playground/src/surfaces/react/previews/TogglePreview.tsx
import { togglePlaygroundMeta, togglePlaygroundSpec } from '@verbb/plugin-kit-playground';

import { toggleReactSectionRenderers } from '../toggle-sections.js';
import { PlaygroundFromSpec } from '../shared/PlaygroundFromSpec.js';
import type { SurfacePreviewDefinition } from '../types.js';

function TogglePreviewPage() {
    return (
        <PlaygroundFromSpec
            spec={togglePlaygroundSpec}
            sectionRenderers={toggleReactSectionRenderers}
        />
    );
}

export const togglePreview: SurfacePreviewDefinition = {
    id: 'toggle',
    title: togglePlaygroundMeta.title,
    description: togglePlaygroundMeta.description,
    Component: TogglePreviewPage,
};

// plugin-kit-playground/src/surfaces/vue/previews/TogglePreview.vue
<script setup lang="ts">
import { togglePlaygroundSpec } from '@verbb/plugin-kit-playground';

import PlaygroundFromSpec from '../shared/PlaygroundFromSpec.vue';
import { toggleVueSectionComponents } from '../toggle-sections/index.js';
</script>

<template>
  <PlaygroundFromSpec
    :spec="togglePlaygroundSpec"
    :section-components="toggleVueSectionComponents"
  />
</template>
