// plugin-kit-playground/src/surfaces/react/previews/TooltipPreview.tsx
import { tooltipPlaygroundMeta, tooltipPlaygroundSpec } from '@verbb/plugin-kit-playground';

import { tooltipReactSectionRenderers } from '../tooltip-sections.js';
import { PlaygroundFromSpec } from '../shared/PlaygroundFromSpec.js';
import type { SurfacePreviewDefinition } from '../types.js';

function TooltipPreviewPage() {
    return (
        <PlaygroundFromSpec
            spec={tooltipPlaygroundSpec}
            sectionRenderers={tooltipReactSectionRenderers}
        />
    );
}

export const tooltipPreview: SurfacePreviewDefinition = {
    id: 'tooltip',
    title: tooltipPlaygroundMeta.title,
    description: tooltipPlaygroundMeta.description,
    Component: TooltipPreviewPage,
};

// plugin-kit-playground/src/surfaces/vue/previews/TooltipPreview.vue
<script setup lang="ts">
import { tooltipPlaygroundSpec } from '@verbb/plugin-kit-playground';

import PlaygroundFromSpec from '../shared/PlaygroundFromSpec.vue';
import { tooltipVueSectionComponents } from '../tooltip-sections/index.js';
</script>

<template>
  <PlaygroundFromSpec
    :spec="tooltipPlaygroundSpec"
    :section-components="tooltipVueSectionComponents"
  />
</template>
