// plugin-kit-playground/src/surfaces/vue/shared/PlaygroundFromSpec.vue
<script setup lang="ts">
import type { Component } from 'vue';
import type { PlaygroundSpec } from '@verbb/plugin-kit-playground';

defineProps<{
    spec: PlaygroundSpec;
    sectionComponents: Record<string, Component>;
}>();
</script>

<template>
  <div class="pg-page">
    <div class="pg-page__hero">
      <div class="pg-page__eyebrow">{{ spec.meta.eyebrow }}</div>
      <h1 class="pg-page__title">{{ spec.meta.title }}</h1>
      <p class="pg-page__lead">{{ spec.meta.description }}</p>
    </div>

    <div class="pg-sections">
      <section v-for="section in spec.sections" :key="section.id" class="pg-section">
        <div class="pg-section__intro">
          <h2 class="pg-section__title">{{ section.title }}</h2>
          <p class="pg-section__description">{{ section.description }}</p>
        </div>

        <div class="pg-section__preview" :data-section-id="section.id">
          <component
            :is="sectionComponents[section.id]"
            v-if="section.bare && sectionComponents[section.id]"
          />
          <div
            v-else-if="sectionComponents[section.id]"
            :class="section.overflowVisible ? 'pg-card pg-card--overflow-visible' : 'pg-card'"
          >
            <div class="pg-card__inner">
              <component :is="sectionComponents[section.id]" />
            </div>
          </div>
        </div>
      </section>
    </div>
  </div>
</template>

// plugin-kit-playground/src/surfaces/react/shared/PlaygroundFromSpec.tsx
import type { ReactNode } from 'react';
import type { PlaygroundSpec } from '@verbb/plugin-kit-playground';

import { PlaygroundPage, PlaygroundSection, PreviewCard } from './playgroundLayouts.js';

export type PlaygroundSectionReactRenderer = () => ReactNode;

export type PlaygroundSectionReactRendererMap = Record<string, PlaygroundSectionReactRenderer>;

type PlaygroundFromSpecProps = {
    spec: PlaygroundSpec;
    sectionRenderers: PlaygroundSectionReactRendererMap;
};

/**
 * Shared playground page shell — section order/copy comes from the spec;
 * each surface supplies real framework previews via sectionRenderers.
 */
export function PlaygroundFromSpec({ spec, sectionRenderers }: PlaygroundFromSpecProps) {
    return (
        <PlaygroundPage
            eyebrow={spec.meta.eyebrow}
            title={spec.meta.title}
            description={spec.meta.description}
        >
            {spec.sections.map((section) => {
                const renderPreview = sectionRenderers[section.id];

                return (
                    <PlaygroundSection
                        key={section.id}
                        title={section.title}
                        description={section.description}
                    >
                        <div className="pg-section__preview" data-section-id={section.id}>
                            {renderPreview ? (
                                section.bare ? (
                                    renderPreview()
                                ) : (
                                    <PreviewCard overflowVisible={section.overflowVisible}>
                                        {renderPreview()}
                                    </PreviewCard>
                                )
                            ) : null}
                        </div>
                    </PlaygroundSection>
                );
            })}
        </PlaygroundPage>
    );
}
