// plugin-kit-playground/src/surfaces/vue/previews/ButtonGroupPreview.vue
<script setup lang="ts">
import { buttonGroupPlaygroundSpec } from '@verbb/plugin-kit-playground';

import PlaygroundFromSpec from '../shared/PlaygroundFromSpec.vue';
import { buttonGroupVueSectionComponents } from '../button-group-sections/index.js';
</script>

<template>
  <PlaygroundFromSpec
    :spec="buttonGroupPlaygroundSpec"
    :section-components="buttonGroupVueSectionComponents"
  />
</template>

// plugin-kit-playground/src/surfaces/react/previews/ButtonGroupPreview.tsx
import { buttonGroupPlaygroundMeta, buttonGroupPlaygroundSpec } from '@verbb/plugin-kit-playground';

import { PlaygroundFromSpec } from '../shared/PlaygroundFromSpec.js';
import { buttonGroupReactSectionRenderers } from '../button-group-sections.js';
import type { SurfacePreviewDefinition } from '../types.js';

function ButtonGroupPreviewPage() {
    return (
        <PlaygroundFromSpec
            spec={buttonGroupPlaygroundSpec}
            sectionRenderers={buttonGroupReactSectionRenderers}
        />
    );
}

export const buttonGroupPreview: SurfacePreviewDefinition = {
    id: 'button-group',
    title: buttonGroupPlaygroundMeta.title,
    description: buttonGroupPlaygroundMeta.description,
    Component: ButtonGroupPreviewPage,
};
