// plugin-kit-playground/src/surfaces/vue/previews/CheckboxPreview.vue
<script setup lang="ts">
import { checkboxPlaygroundSpec } from '@verbb/plugin-kit-playground';

import PlaygroundFromSpec from '../shared/PlaygroundFromSpec.vue';
import { checkboxVueSectionComponents } from '../spec-sections.js';
</script>

<template>
  <PlaygroundFromSpec
    :spec="checkboxPlaygroundSpec"
    :section-components="checkboxVueSectionComponents"
  />
</template>

// plugin-kit-playground/src/surfaces/react/previews/CheckboxPreview.tsx
import { checkboxPlaygroundMeta, checkboxPlaygroundSpec } from '@verbb/plugin-kit-playground';

import { checkboxReactSectionRenderers } from '../checkbox-sections.js';
import { PlaygroundFromSpec } from '../shared/PlaygroundFromSpec.js';
import type { SurfacePreviewDefinition } from '../types.js';

function CheckboxPreviewPage() {
    return (
        <PlaygroundFromSpec
            spec={checkboxPlaygroundSpec}
            sectionRenderers={checkboxReactSectionRenderers}
        />
    );
}

export const checkboxPreview: SurfacePreviewDefinition = {
    id: 'checkbox',
    title: checkboxPlaygroundMeta.title,
    description: checkboxPlaygroundMeta.description,
    Component: CheckboxPreviewPage,
};
