// plugin-kit-playground/src/surfaces/vue/previews/CodeEditorPreview.vue
<script setup lang="ts">
import { codeEditorPlaygroundSpec } from '@verbb/plugin-kit-playground';

import PlaygroundFromSpec from '../shared/PlaygroundFromSpec.vue';
import { codeEditorVueSectionComponents } from '../code-editor-sections/index.js';
</script>

<template>
  <PlaygroundFromSpec
    :spec="codeEditorPlaygroundSpec"
    :section-components="codeEditorVueSectionComponents"
  />
</template>

// plugin-kit-playground/src/surfaces/react/previews/CodeEditorPreview.tsx
import { codeEditorPlaygroundMeta, codeEditorPlaygroundSpec } from '@verbb/plugin-kit-playground';

import { codeEditorReactSectionRenderers } from '../code-editor-sections.js';
import { PlaygroundFromSpec } from '../shared/PlaygroundFromSpec.js';
import type { SurfacePreviewDefinition } from '../types.js';

function CodeEditorPreviewPage() {
    return (
        <PlaygroundFromSpec
            spec={codeEditorPlaygroundSpec}
            sectionRenderers={codeEditorReactSectionRenderers}
        />
    );
}

export const codeEditorPreview: SurfacePreviewDefinition = {
    id: 'code-editor',
    title: codeEditorPlaygroundMeta.title,
    description: codeEditorPlaygroundMeta.description,
    Component: CodeEditorPreviewPage,
};
