// plugin-kit-playground/src/surfaces/vue/previews/DatePickerPreview.vue
<script setup lang="ts">
import { datePickerPlaygroundSpec } from '@verbb/plugin-kit-playground';

import PlaygroundFromSpec from '../shared/PlaygroundFromSpec.vue';
import { datePickerVueSectionComponents } from '../date-picker-sections/index.js';
</script>

<template>
  <PlaygroundFromSpec
    :spec="datePickerPlaygroundSpec"
    :section-components="datePickerVueSectionComponents"
  />
</template>

// plugin-kit-playground/src/surfaces/react/previews/DatePickerPreview.tsx
import { datePickerPlaygroundMeta, datePickerPlaygroundSpec } from '@verbb/plugin-kit-playground';

import { datePickerReactSectionRenderers } from '../date-picker-sections.js';
import { PlaygroundFromSpec } from '../shared/PlaygroundFromSpec.js';
import type { SurfacePreviewDefinition } from '../types.js';

function DatePickerPreviewPage() {
    return (
        <PlaygroundFromSpec
            spec={datePickerPlaygroundSpec}
            sectionRenderers={datePickerReactSectionRenderers}
        />
    );
}

export const datePickerPreview: SurfacePreviewDefinition = {
    id: 'date-picker',
    title: datePickerPlaygroundMeta.title,
    description: datePickerPlaygroundMeta.description,
    Component: DatePickerPreviewPage,
};
