// plugin-kit-playground/src/surfaces/vue/previews/DialogPreview.vue
<script setup lang="ts">
import { dialogPlaygroundSpec } from '@verbb/plugin-kit-playground';

import PlaygroundFromSpec from '../shared/PlaygroundFromSpec.vue';
import { dialogVueSectionComponents } from '../dialog-sections/index.js';
</script>

<template>
  <PlaygroundFromSpec
    :spec="dialogPlaygroundSpec"
    :section-components="dialogVueSectionComponents"
  />
</template>

// plugin-kit-playground/src/surfaces/react/previews/DialogPreview.tsx
import { dialogPlaygroundMeta, dialogPlaygroundSpec } from '@verbb/plugin-kit-playground';

import { dialogReactSectionRenderers } from '../dialog-sections.js';
import { PlaygroundFromSpec } from '../shared/PlaygroundFromSpec.js';
import type { SurfacePreviewDefinition } from '../types.js';

function DialogPreviewPage() {
    return (
        <PlaygroundFromSpec
            spec={dialogPlaygroundSpec}
            sectionRenderers={dialogReactSectionRenderers}
        />
    );
}

export const dialogPreview: SurfacePreviewDefinition = {
    id: 'dialog',
    title: dialogPlaygroundMeta.title,
    description: dialogPlaygroundMeta.description,
    Component: DialogPreviewPage,
};
