// plugin-kit-playground/src/surfaces/vue/previews/LightswitchPreview.vue
<script setup lang="ts">
import { lightswitchPlaygroundSpec } from '@verbb/plugin-kit-playground';

import PlaygroundFromSpec from '../shared/PlaygroundFromSpec.vue';
import { lightswitchVueSectionComponents } from '../lightswitch-sections/index.js';
</script>

<template>
  <PlaygroundFromSpec
    :spec="lightswitchPlaygroundSpec"
    :section-components="lightswitchVueSectionComponents"
  />
</template>

// plugin-kit-playground/src/surfaces/react/previews/LightswitchPreview.tsx
import { lightswitchPlaygroundMeta, lightswitchPlaygroundSpec } from '@verbb/plugin-kit-playground';

import { lightswitchReactSectionRenderers } from '../lightswitch-sections.js';
import { PlaygroundFromSpec } from '../shared/PlaygroundFromSpec.js';
import type { SurfacePreviewDefinition } from '../types.js';

function LightswitchPreviewPage() {
    return (
        <PlaygroundFromSpec
            spec={lightswitchPlaygroundSpec}
            sectionRenderers={lightswitchReactSectionRenderers}
        />
    );
}

export const lightswitchPreview: SurfacePreviewDefinition = {
    id: 'lightswitch',
    title: lightswitchPlaygroundMeta.title,
    description: lightswitchPlaygroundMeta.description,
    Component: LightswitchPreviewPage,
};
