// plugin-kit-playground/src/surfaces/vue/previews/ScrollAreaPreview.vue
<script setup lang="ts">
import { scrollAreaPlaygroundSpec } from '@verbb/plugin-kit-playground';

import PlaygroundFromSpec from '../shared/PlaygroundFromSpec.vue';
import { scrollAreaVueSectionComponents } from '../scroll-area-sections/index.js';
</script>

<template>
  <PlaygroundFromSpec
    :spec="scrollAreaPlaygroundSpec"
    :section-components="scrollAreaVueSectionComponents"
  />
</template>

// plugin-kit-playground/src/surfaces/react/previews/ScrollAreaPreview.tsx
import { scrollAreaPlaygroundMeta, scrollAreaPlaygroundSpec } from '@verbb/plugin-kit-playground';

import { scrollAreaReactSectionRenderers } from '../scroll-area-sections.js';
import { PlaygroundFromSpec } from '../shared/PlaygroundFromSpec.js';
import type { SurfacePreviewDefinition } from '../types.js';

function ScrollAreaPreviewPage() {
    return (
        <PlaygroundFromSpec
            spec={scrollAreaPlaygroundSpec}
            sectionRenderers={scrollAreaReactSectionRenderers}
        />
    );
}

export const scrollAreaPreview: SurfacePreviewDefinition = {
    id: 'scroll-area',
    title: scrollAreaPlaygroundMeta.title,
    description: scrollAreaPlaygroundMeta.description,
    Component: ScrollAreaPreviewPage,
};
