// plugin-kit-playground/src/surfaces/vue/previews/SelectPreview.vue
<script setup lang="ts">
import { selectPlaygroundSpec } from '@verbb/plugin-kit-playground';

import PlaygroundFromSpec from '../shared/PlaygroundFromSpec.vue';
import { selectVueSectionComponents } from '../select-sections/index.js';
</script>

<template>
  <PlaygroundFromSpec
    :spec="selectPlaygroundSpec"
    :section-components="selectVueSectionComponents"
  />
</template>

// plugin-kit-playground/src/surfaces/react/previews/SelectPreview.tsx
import { selectPlaygroundMeta, selectPlaygroundSpec } from '@verbb/plugin-kit-playground';

import { selectReactSectionRenderers } from '../select-sections.js';
import { PlaygroundFromSpec } from '../shared/PlaygroundFromSpec.js';
import type { SurfacePreviewDefinition } from '../types.js';

function SelectPreviewPage() {
    return (
        <PlaygroundFromSpec
            spec={selectPlaygroundSpec}
            sectionRenderers={selectReactSectionRenderers}
        />
    );
}

export const selectPreview: SurfacePreviewDefinition = {
    id: 'select',
    title: selectPlaygroundMeta.title,
    description: selectPlaygroundMeta.description,
    Component: SelectPreviewPage,
};
