// plugin-kit-playground/src/surfaces/vue/previews/SeparatorPreview.vue
<script setup lang="ts">
import { separatorPlaygroundSpec } from '@verbb/plugin-kit-playground';

import PlaygroundFromSpec from '../shared/PlaygroundFromSpec.vue';
import { separatorVueSectionComponents } from '../separator-sections/index.js';
</script>

<template>
  <PlaygroundFromSpec
    :spec="separatorPlaygroundSpec"
    :section-components="separatorVueSectionComponents"
  />
</template>

// plugin-kit-playground/src/surfaces/react/previews/SeparatorPreview.tsx
import { separatorPlaygroundMeta, separatorPlaygroundSpec } from '@verbb/plugin-kit-playground';

import { separatorReactSectionRenderers } from '../separator-sections.js';
import { PlaygroundFromSpec } from '../shared/PlaygroundFromSpec.js';
import type { SurfacePreviewDefinition } from '../types.js';

function SeparatorPreviewPage() {
    return (
        <PlaygroundFromSpec
            spec={separatorPlaygroundSpec}
            sectionRenderers={separatorReactSectionRenderers}
        />
    );
}

export const separatorPreview: SurfacePreviewDefinition = {
    id: 'separator',
    title: separatorPlaygroundMeta.title,
    description: separatorPlaygroundMeta.description,
    Component: SeparatorPreviewPage,
};
