// plugin-kit-playground/src/surfaces/vue/previews/TextareaPreview.vue
<script setup lang="ts">
import { textareaPlaygroundSpec } from '@verbb/plugin-kit-playground';

import PlaygroundFromSpec from '../shared/PlaygroundFromSpec.vue';
import { textareaVueSectionComponents } from '../textarea-sections/index.js';
</script>

<template>
  <PlaygroundFromSpec
    :spec="textareaPlaygroundSpec"
    :section-components="textareaVueSectionComponents"
  />
</template>

// plugin-kit-playground/src/surfaces/react/previews/TextareaPreview.tsx
import { textareaPlaygroundMeta, textareaPlaygroundSpec } from '@verbb/plugin-kit-playground';

import { textareaReactSectionRenderers } from '../textarea-sections.js';
import { PlaygroundFromSpec } from '../shared/PlaygroundFromSpec.js';
import type { SurfacePreviewDefinition } from '../types.js';

function TextareaPreviewPage() {
    return (
        <PlaygroundFromSpec
            spec={textareaPlaygroundSpec}
            sectionRenderers={textareaReactSectionRenderers}
        />
    );
}

export const textareaPreview: SurfacePreviewDefinition = {
    id: 'textarea',
    title: textareaPlaygroundMeta.title,
    description: textareaPlaygroundMeta.description,
    Component: TextareaPreviewPage,
};
