// plugin-kit-playground/src/surfaces/vue/previews/ToggleGroupPreview.vue
<script setup lang="ts">
import { toggleGroupPlaygroundSpec } from '@verbb/plugin-kit-playground';

import PlaygroundFromSpec from '../shared/PlaygroundFromSpec.vue';
import { toggleGroupVueSectionComponents } from '../toggle-group-sections/index.js';
</script>

<template>
  <PlaygroundFromSpec
    :spec="toggleGroupPlaygroundSpec"
    :section-components="toggleGroupVueSectionComponents"
  />
</template>

// plugin-kit-playground/src/surfaces/react/previews/ToggleGroupPreview.tsx
import { toggleGroupPlaygroundMeta, toggleGroupPlaygroundSpec } from '@verbb/plugin-kit-playground';

import { toggleGroupReactSectionRenderers } from '../toggle-group-sections.js';
import { PlaygroundFromSpec } from '../shared/PlaygroundFromSpec.js';
import type { SurfacePreviewDefinition } from '../types.js';

function ToggleGroupPreviewPage() {
    return (
        <PlaygroundFromSpec
            spec={toggleGroupPlaygroundSpec}
            sectionRenderers={toggleGroupReactSectionRenderers}
        />
    );
}

export const toggleGroupPreview: SurfacePreviewDefinition = {
    id: 'toggle-group',
    title: toggleGroupPlaygroundMeta.title,
    description: toggleGroupPlaygroundMeta.description,
    Component: ToggleGroupPreviewPage,
};
